sudo: false

language:
  - python

python:
  - 3.6

install:
  - pip install --upgrade ruamel.yaml mypy pytest pytest-cov pylint coveralls
  - gem install hiera-eyaml

script:
  - pip install -e .
  - mypy yamlpath
  - pylint yamlpath
  - pytest --verbose --cov=yamlpath --cov-report=term-missing --cov-fail-under=98 tests
  - coveralls

deploy:
  provider: pypi
  user: wwkimball
  password:
    secure: "cBWRVvQibxw2KTYJoruKeOA1vNDk2+ZuZsAzW9hq3bk2Ab4GDy7G8pYRhVhiHNMDY0w5+Ii66/i0ERpBC95bi7Mzy/NOzbhoYflr+lDOoC6YR76VpCyHJQ/I3YmyTjSeWqB86JLfmQNi9RJWBbZYWpsCuEjBRP7w6oOf2QdAefQUctJ9g69Gt5r7okNm4nfbiAwvUAjGBT7dSRKPrMmRhP8Qc5ugXrO3xNnh9xCBqBkvXfDQjlA3YCi3RiuWJQHkwIhHjfwoDXzis4bprBQUOAZ/+c6WiCvEsMsG1551Ilt7Q1x6aiu98m4hYkZMTIl5IjCMSXbnlOSdlv0XvO8jSq/+GGSdI6EbLAYC1MTnob7w1/NQSsVfz6dKl/pMCRC2J+OGNqv5a3Ln3rzeOTs9opZunHQ34Ro+MxEKSf+XdU48YJR1DlDLWYV9tbiVFG+tSybu3uxcs825EB4aNzL7pMBaIzMpEjhsDNEDZ90T6jDnLzJHYFgH3yj9ortpjYI3CZdvzsVqQrTT1zXzKzMbW6/o0U8azzGQWu24Bn6HSe3Cr0PQQpalSyN/usZziBwLYVj42d3tCtg1xGNUvzgX1mRst8Ltsag4g4OG54IJ4RihcviQWLY6Jgjnob5KU3JcCYzKJjKu5cXyuK2ec7lMCBRaVo6qaiP1iVPNLpXsqz4="
  skip_existing: true
  on:
    tags: true

notifications:
  email: false
